packages:
  - "packages/*"
  - "apps/*"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
minimumReleaseAgeExclude:
  - '@clerk/backend@3.7.1'
  - '@clerk/nextjs@7.5.3'
  - '@clerk/react@6.10.0'
  - '@clerk/shared@4.18.0'
  - '@clerk/testing@2.1.2'
